export const GESTURE_META = {
  next: {
    id: 'next',
    number: '01',
    icon: '✋',
    label: 'Next Slide',
    editorialName: 'Open Palm',
    editorialAction: 'ADVANCE DECK ■ 01',
    hint: 'Open palm → advance',
    description: 'All five fingers extended vertically. Triggers an instantaneous, smooth slide advance to the following slide.',
    fingerRule: 'Thumb, Index, Middle, Ring & Pinky all extended above MCP joints.',
    confidence: '95% Confidence',
    color: '#D4AF37', // warm champagne / gold
    textColor: 'text-[#D4AF37]',
    borderColor: 'border-[#D4AF37]/40',
    bgBadge: 'bg-[#D4AF37]/10',
  },
  prev: {
    id: 'prev',
    number: '02',
    icon: '✊',
    label: 'Prev Slide',
    editorialName: 'Closed Fist',
    editorialAction: 'REVERSE DECK ■ 02',
    hint: 'Fist → go back',
    description: 'All five fingers closed tight into the palm. Smoothly steps back to the prior slide in the presentation.',
    fingerRule: 'All five fingertips folded below MCP boundary threshold.',
    confidence: '94% Confidence',
    color: '#D6C5A9',
    textColor: 'text-[#D6C5A9]',
    borderColor: 'border-[#D6C5A9]/40',
    bgBadge: 'bg-[#D6C5A9]/10',
  },
  first: {
    id: 'first',
    number: '03',
    icon: '☝️',
    label: 'First Slide',
    editorialName: 'Index Extended',
    editorialAction: 'RESET DECK ■ 03',
    hint: 'Index up → slide 1',
    description: 'Index finger pointed upward with thumb and remaining fingers retracted. Immediately returns presentation to Slide 01.',
    fingerRule: 'Only index finger extended; thumb, middle, ring, pinky curled.',
    confidence: '96% Confidence',
    color: '#C0C4CC',
    textColor: 'text-zinc-300',
    borderColor: 'border-zinc-400/40',
    bgBadge: 'bg-white/10',
  },
  last: {
    id: 'last',
    number: '04',
    icon: '🤙',
    label: 'Last Slide',
    editorialName: 'Call-Me / Shaka',
    editorialAction: 'JUMP TO FINALE ■ 04',
    hint: 'Call me → last slide',
    description: 'Thumb and pinky outstretched with central fingers curled. Navigates straight to the conclusion / final slide.',
    fingerRule: 'Thumb and pinky extended; index, middle, ring curled.',
    confidence: '93% Confidence',
    color: '#A8B3C4',
    textColor: 'text-slate-300',
    borderColor: 'border-slate-400/40',
    bgBadge: 'bg-slate-500/10',
  },
  none: {
    id: 'none',
    number: '00',
    icon: '👋',
    label: 'Searching Hand',
    editorialName: 'Idle / Ready',
    editorialAction: 'AWAITING INTENT ■ 00',
    hint: 'Raise hand into view',
    description: 'Optical detection active. Waiting for hand landmarks within camera field of view.',
    fingerRule: 'No stable gesture matched or hand out of frame.',
    confidence: 'Standby',
    color: '#71717a',
    textColor: 'text-zinc-400',
    borderColor: 'border-zinc-700/40',
    bgBadge: 'bg-zinc-800/20',
  },
};

export const DEFAULT_EDITORIAL_SLIDES = [
  {
    id: 1,
    tag: 'SYSTEM 01 // OVERVIEW',
    title: 'Unfettered Command',
    subtitle: 'Touch-free presentation dynamics driven by real-time spatial computer vision.',
    caption: 'LATENCY < 12MS • 60 FPS • LOCAL WASM',
    quote: '“The stage belongs to your natural presence. No clickers, no broken eye contact, no friction.”',
    accent: '01 / 05',
    graphicType: 'kinetic-hand',
  },
  {
    id: 2,
    tag: 'VISION 02 // PIPELINE',
    title: '21 3D Spatial Landmarks',
    subtitle: 'Instantaneous finger joint vector triangulation running directly on your client hardware.',
    caption: 'MEDIAPIPE HANDS • ON-DEVICE NEURAL MESH',
    quote: '“Sub-pixel spatial accuracy translates anatomical micro-movements into flawless navigation.”',
    accent: '02 / 05',
    graphicType: 'mesh-reticle',
  },
  {
    id: 3,
    tag: 'DYNAMICS 03 // CONTINUITY',
    title: 'Intelligent Debouncing',
    subtitle: 'Heuristic state machine filters conversational gestures from deliberate directional commands.',
    caption: 'COOLDOWN DYNAMICS • FALSE-TRIGGER MITIGATION',
    quote: '“Speak naturally with expressive gestures. The system only executes when intentional.”',
    accent: '03 / 05',
    graphicType: 'signal-wave',
  },
  {
    id: 4,
    tag: 'PRIVACY 04 // ZERO CLOUD',
    title: 'Sovereign Architecture',
    subtitle: 'Zero video or telemetry data leaves your local machine. Pure browser-native computing.',
    caption: 'AIR-GAPPED COMPATIBLE • ZERO SERVER CALLS',
    quote: '“Your confidential presentations and video stream never touch an external network.”',
    accent: '04 / 05',
    graphicType: 'shield-rings',
  },
  {
    id: 5,
    tag: 'PERFORMANCE 05 // RETINA',
    title: 'High-DPI PDF Vector Engine',
    subtitle: 'Retina-sharp canvas scaling with high devicePixelRatio support and smooth GPU transitions.',
    caption: 'PDF.JS + HARDWARE ACCELERATED CANVAS',
    quote: '“Pitch decks, technical schematics, and typography rendered with laser precision.”',
    accent: '05 / 05',
    graphicType: 'vector-grid',
  },
];
