export const GESTURE_META = {
  next: {
    id: 'next',
    icon: '✋',
    label: 'Next Slide',
    hint: 'Open palm → advance',
    color: '#4ade80',
    textColor: 'text-green-400',
    borderColor: 'border-green-500/40',
  },
  prev: {
    id: 'prev',
    icon: '✊',
    label: 'Prev Slide',
    hint: 'Fist → go back',
    color: '#fb923c',
    textColor: 'text-orange-400',
    borderColor: 'border-orange-500/40',
  },
  first: {
    id: 'first',
    icon: '☝️',
    label: 'First Slide',
    hint: 'Index up → slide 1',
    color: '#60a5fa',
    textColor: 'text-blue-400',
    borderColor: 'border-blue-500/40',
  },
  last: {
    id: 'last',
    icon: '🤙',
    label: 'Last Slide',
    hint: 'Call me → last slide',
    color: '#c084fc',
    textColor: 'text-purple-400',
    borderColor: 'border-purple-500/40',
  },
  none: {
    id: 'none',
    icon: '👋',
    label: 'Show a gesture',
    hint: 'Instant detection',
    color: '#71717a',
    textColor: 'text-zinc-500',
    borderColor: 'border-zinc-700/40',
  },
};
